### ISSUE TITLE
Prevent adding sensitive content in validation error description

### ISSUE THREAD

**Issue by celcius112** [ekino/spring-boot-starter-errors#109]
When a `MethodArgumentNotValidException` is thrown the description contains information about the method handling the endpoint. For instance: 
```
{
...
    "description": "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.example.Response> com.example.Controller.get(com.example.Request): [Field error in object 'request' on field 'size': rejected value [0]; ...",
...
}
```
Similar to the `display-full-stacktrace` property, another property could be added in order to opt-in to this kind of description.

**Comment by clemstoquart** [comment]
Hi,

I agree. A PR would be very welcome :)
